#!/usr/bin/env python3
"""
Generates a type-safe Swift enum from Localizable.xcstrings.

Usage:
  python3 scripts/generate_strings.py

Add as an Xcode Run Script build phase (before Compile Sources):
  python3 "$SRCROOT/scripts/generate_strings.py"
"""
import json
import re
import sys
from pathlib import Path

XCSTRINGS_PATH = "HabitHuddle-iOS/Localizable.xcstrings"
OUTPUT_PATH    = "HabitHuddle-iOS/Generated/Strings+Generated.swift"

# Matches a full printf specifier including length modifiers (hh, h, ll, l, q, L, z)
# Examples: %@  %d  %ld  %lld  %f  %s
FORMAT_SPEC_RE = re.compile(r'%(?:\d+\$)?(?:[hHlLqZzt]*)([diouxXeEfFgGaAcsp@])')

SWIFT_KEYWORDS = {
    "as", "break", "case", "catch", "class", "continue", "default", "defer",
    "do", "else", "enum", "extension", "fallthrough", "false", "for", "func",
    "guard", "if", "import", "in", "init", "inout", "is", "let", "nil",
    "operator", "precedencegroup", "protocol", "repeat", "rethrows", "return",
    "self", "static", "struct", "subscript", "super", "switch", "throw",
    "throws", "true", "try", "type", "typealias", "var", "where", "while",
}

HEADER = """\
// Generated by scripts/generate_strings.py — do not edit.
// Re-run when Localizable.xcstrings changes:
//   python3 scripts/generate_strings.py
// swiftlint:disable all
import SwiftUI

// MARK: - L10n

/// Type-safe access to all localised strings.
///
/// - Simple strings  → `LocalizedStringKey`, usable directly in `Text(L10n.xxx)`.
/// - Format strings  → `func`, returns `String` via `String(localized:)`.
enum L10n {
"""
FOOTER = "}\n"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def key_to_identifier(key: str, max_words: int = 5):
    """Derive a camelCase Swift identifier from a catalog key."""
    # Drop format specifiers so they don't pollute the name
    clean = FORMAT_SPEC_RE.sub(' ', key)
    # Drop emoji and other non-ASCII
    clean = re.sub(r'[^\x00-\x7F]', ' ', clean)
    # Split on anything that isn't alphanumeric
    words = [w for w in re.split(r'[^a-zA-Z0-9]+', clean) if len(w) >= 2][:max_words]
    if not words:
        return None
    ident = words[0][0].lower() + words[0][1:]
    for w in words[1:]:
        ident += w[0].upper() + w[1:]
    if not ident or not ident[0].isalpha():
        ident = 'key' + ident
    if ident in SWIFT_KEYWORDS:
        ident = '`' + ident + '`'
    return ident


def format_specifiers(key: str):
    """Return the ordered list of type characters from printf specifiers in the key."""
    return [m.group(1) for m in FORMAT_SPEC_RE.finditer(key)]


def has_plurals(entry: dict) -> bool:
    for loc in entry.get('localizations', {}).values():
        if 'variations' in loc:
            return True
    return False


def key_to_interpolated_literal(key: str) -> str:
    """
    Turn a printf-style key into a Swift string literal with `\\(pN)` interpolation.
    e.g. "%@ challenged you!" -> "\\(p1) challenged you!"
    Also escapes characters that need escaping inside a Swift string literal.
    """
    counters = {'str': 0, 'int': 0, 'other': 0}

    def replacer(m: re.Match) -> str:
        spec = m.group(1)
        if spec == '@':
            counters['str'] += 1
            return f'\\(p{counters["str"]})'
        elif spec in ('d', 'i', 'o', 'u', 'x', 'X'):
            counters['int'] += 1
            return f'\\(p{counters["int"]})'
        else:
            counters['other'] += 1
            return f'\\(p{counters["other"]})'

    result = FORMAT_SPEC_RE.sub(replacer, key)

    # Escape characters that are special inside a Swift string literal
    # (backslash already handled by the replacer, just handle quotes and newlines)
    result = result.replace('\\', '\\\\')  # escape backslashes first ...
    # ... but undo the escaping of our \(pN) placeholders
    result = result.replace('\\\\(p', '\\(p')
    result = result.replace('"', '\\"')
    result = result.replace('\n', '\\n')

    # Curly/smart quotes → Unicode escapes so the literal is portable
    result = result.replace('“', '\\u{201C}')
    result = result.replace('”', '\\u{201D}')

    return result


def param_list(specifiers: list[str]) -> str:
    """Build a Swift parameter list from a list of printf specifiers."""
    params = []
    str_n = int_n = other_n = 0
    for spec in specifiers:
        if spec == '@':
            str_n += 1
            params.append(f'_ p{str_n}: String')
        elif spec in ('d', 'i', 'o', 'u', 'x', 'X'):
            int_n += 1
            params.append(f'_ p{int_n}: Int')
        else:
            other_n += 1
            params.append(f'_ p{other_n}: Any')
    return ', '.join(params)


def escape_for_localizedstringkey(key: str) -> str:
    """Escape a plain key for use as a Swift string literal (LocalizedStringKey)."""
    key = key.replace('\\', '\\\\')
    key = key.replace('"', '\\"')
    key = key.replace('\n', '\\n')
    key = key.replace('“', '\\u{201C}')
    key = key.replace('”', '\\u{201D}')
    return key


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

def generate(xcstrings_data: dict) -> str:
    strings: dict = xcstrings_data.get('strings', {})

    lines: list[str] = [HEADER]

    used_idents: dict[str, int] = {}
    skipped = 0

    for key in sorted(strings.keys()):
        if not key:
            continue

        entry   = strings[key]
        comment = entry.get('comment', '')
        specs   = format_specifiers(key)
        plural  = has_plurals(entry)
        is_fmt  = bool(specs) or plural

        ident = key_to_identifier(key)
        if not ident:
            skipped += 1
            continue

        # Deduplicate
        if ident in used_idents:
            used_idents[ident] += 1
            ident = f'{ident}{used_idents[ident]}'
        else:
            used_idents[ident] = 0

        # Comment
        if comment:
            lines.append(f'    /// {comment}')

        if not is_fmt:
            escaped = escape_for_localizedstringkey(key)
            lines.append(f'    static var {ident}: LocalizedStringKey {{ "{escaped}" }}')
        else:
            params   = param_list(specs)
            literal  = key_to_interpolated_literal(key)
            lines.append(f'    static func {ident}({params}) -> String {{')
            lines.append(f'        String(localized: "{literal}")')
            lines.append( '    }')

        lines.append('')

    lines.append(FOOTER)

    print(f'  {len(strings) - skipped} entries written, {skipped} skipped',
          file=sys.stderr)
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    root = Path(__file__).parent.parent  # project root
    xcstrings_path = root / XCSTRINGS_PATH
    output_path    = root / OUTPUT_PATH

    if not xcstrings_path.exists():
        print(f'Error: {xcstrings_path} not found', file=sys.stderr)
        sys.exit(1)

    with open(xcstrings_path, encoding='utf-8') as f:
        data = json.load(f)

    swift = generate(data)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(swift)

    print(f'Generated {output_path.relative_to(root)}')


if __name__ == '__main__':
    main()
